model:
  dropout: 0.2
  num_heads: 8
  num_layers: 1
  backbone: "ViT-B/16"
  dataset_name: "CUB-200-2011"
  use_cache: False

checkpoint:
  enabled: true
  cache_dir: "checkpoints"

training:
  epochs: 10
  batch_size: 8
  mode: "logits"
  device: "cuda:0"
  precision: "fp32"
  optimizer: "SGD"
  use_cutout: false
  increment_epochs: 0
  learning_rate: 0.001
  weight_decay: 0.0005
  confusion_matrix: false
  visualize_gradcam: false
  class_distribution: false
  visualize_attention: false

data:
  kshot: 1
  seed: 42
  val_size: 0.7
  num_workers: 4
  run_eda: false
  clip_mean: [0.48145466, 0.4578275, 0.40821073]
  clip_std: [0.26862954, 0.26130258, 0.27577711]
  root: "datasets/cub-200-2011-renamed"

active_learning:
  nshot: 1
  rounds: 2
  strategy: alfamix
  mc_samples: 10
  reset_optimizer_per_round: true
  reset_model_per_round: false
  plot_coreset_embedding_umap: false
  plot_coreset_embedding_tsne: false
  plot_entropy_distribution: false
  plot_bald_distribution: false
  plot_conflict_distribution: false

logging:
  output_dir: "outputs/al"