uv run tip_adapter.py --config configs/tip_adapter.yaml --data.all True --model.backbone "RN50"
uv run proto_adapter.py --config configs/proto_adapter.yaml --data.all True --model.backbone "RN50"
uv run ape.py --config configs/ape.yaml --data.all True --model.backbone "RN50"
uv run timo.py --config configs/timo.yaml --data.all True --model.backbone "RN50"
uv run timo.py --config configs/protofuse.yaml --data.all True --model.backbone "RN50"